[project]
name = 'AdStack'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.media-storages]
path = 'contracts/ad-content-registry.clar'
clarity_version = 4
epoch = 'latest'

[contracts.data-collectors]
path = 'contracts/analytics-aggregator.clar'
clarity_version = 4
epoch = 'latest'

[contracts.bidding-platforms]
path = 'contracts/auction-system.clar'
clarity_version = 4
epoch = 'latest'

[contracts.ad-coordinators]
path = 'contracts/campaign-orchestrator.clar'
clarity_version = 4
epoch = 'latest'

[contracts.conflict-resolvers]
path = 'contracts/dispute-resolution.clar'
clarity_version = 4
epoch = 'latest'

[contracts.asset-guardians]
path = 'contracts/escrow-manager.clar'
clarity_version = 4
epoch = 'latest'

[contracts.dao-controllers]
path = 'contracts/governance-dao.clar'
clarity_version = 4
epoch = 'latest'

[contracts.external-feeds]
path = 'contracts/oracle-integration.clar'
clarity_version = 4
epoch = 'latest'

[contracts.payment-processors]
path = 'contracts/revenue-settlement.clar'
clarity_version = 4
epoch = 'latest'

[contracts.network-registrys]
path = 'contracts/publisher-network.clar'
clarity_version = 4
epoch = 'latest'

[contracts.bonus-vaults]
path = 'contracts/rewards-distributor.clar'
clarity_version = 4
epoch = 'latest'

[contracts.billing-systems]
path = 'contracts/subscription-manager.clar'
clarity_version = 4
epoch = 'latest'

[contracts.demographic-filters]
path = 'contracts/targeting-engine.clar'
clarity_version = 4
epoch = 'latest'

[contracts.account-managers]
path = 'contracts/identity-registry.clar'
clarity_version = 4
epoch = 'latest'

[contracts.security-monitors]
path = 'contracts/fraud-prevention.clar'
clarity_version = 4
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
