[project]
name = 'AdStack'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.asset-library]
path = 'contracts/ad-content-registry.clar'
clarity_version = 4
epoch = 'latest'

[contracts.stats-tracker]
path = 'contracts/analytics-aggregator.clar'
clarity_version = 4
epoch = 'latest'

[contracts.offer-exchange]
path = 'contracts/auction-system.clar'
clarity_version = 4
epoch = 'latest'

[contracts.promo-manager]
path = 'contracts/campaign-orchestrator.clar'
clarity_version = 4
epoch = 'latest'

[contracts.mediation-hub]
path = 'contracts/dispute-resolution.clar'
clarity_version = 4
epoch = 'latest'

[contracts.funds-keeper]
path = 'contracts/escrow-manager.clar'
clarity_version = 4
epoch = 'latest'

[contracts.vote-handler]
path = 'contracts/governance-dao.clar'
clarity_version = 4
epoch = 'latest'

[contracts.oracle-link]
path = 'contracts/oracle-integration.clar'
clarity_version = 4
epoch = 'latest'

[contracts.cash-distributor]
path = 'contracts/revenue-settlement.clar'
clarity_version = 4
epoch = 'latest'

[contracts.partner-hub]
path = 'contracts/publisher-network.clar'
clarity_version = 4
epoch = 'latest'

[contracts.prize-pool]
path = 'contracts/rewards-distributor.clar'
clarity_version = 4
epoch = 'latest'

[contracts.subscription-hub]
path = 'contracts/subscription-manager.clar'
clarity_version = 4
epoch = 'latest'

[contracts.audience-selector]
path = 'contracts/targeting-engine.clar'
clarity_version = 4
epoch = 'latest'

[contracts.user-profiles]
path = 'contracts/identity-registry.clar'
clarity_version = 4
epoch = 'latest'

[contracts.threat-detector]
path = 'contracts/fraud-prevention.clar'
clarity_version = 4
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
